### ISSUE TITLE
minor bug in url to laravel snippets

### ISSUE THREAD

**Issue by gnanet** [joshbuchea/awesome-starters#1]
`- [Laravel Snippets](www.laravelsnippets.com) Many laravel snippets.`

should be

`- [Laravel Snippets](http://www.laravelsnippets.com) Many laravel snippets.`

**Comment by joshbuchea** [comment]
@gnanet I think you have the wrong project..?

**Comment by gnanet** [comment]
ARGHH, yes sorry

**Comment by joshbuchea** [comment]
@gnanet no worries 😄
